# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='english_dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_name', models.CharField(max_length=100, verbose_name='\u8bcd\u5e93\u540d')),
                ('details', models.TextField(blank=True, verbose_name='\u8bcd\u5e93\u8be6\u60c5\u63cf\u8ff0')),
                ('words', models.TextField(blank=True, verbose_name='\u8bcd\u5e93\u5355\u8bcd\u5217\u8868')),
            ],
            options={
                'verbose_name_plural': '\u8bcd\u5e93\u8868',
            },
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='\u7528\u6237\u540d')),
                ('dict_name', models.CharField(max_length=100, verbose_name='\u8bcd\u5e93\u540d')),
                ('learned_words', models.TextField(blank=True, verbose_name='\u5df2\u5b66\u4e60\u5355\u8bcd\u5217\u8868')),
            ],
            options={
                'verbose_name_plural': '\u5b66\u4e60\u8be6\u60c5\u8868',
            },
        ),
    ]
